pierregarciafr/wadzatsong

app/views/games/show.html.erb
j'ai cleané le html de la show.
j'ai tout réindenter correctement, virer des div en trop, et mis des commentaires pour bien séparer les différentes parties.
c'est plus clair et ça nous aidera si on doit faire des partials.
je pense qu'il y a 2/3 blocs d'anciens codes qui ne sont plus d'actualité.
on verra lundi ensemble
bon week!
=> clean html of game/show.html.erb

app/views/games/show.html.erb
j'ai intégré à ma version, 
sur la show ligne 113 j'ai ôté le # à <%# if answer.status == true %>, il provoquait une erreur.
je remarque que la vague dans le buzzer est décentrée sur la droite à présent.
=> make it work

app/channels/application_cable/connection.rb, app/channels/game_channel.rb, app/controllers/games_controller.rb, app/controllers/participations_controller.rb, app/javascript/channels/consumer.js, app/javascript/channels/game_channel.js, app/views/games/_game_created.html.erb, app/views/games/_game_finished.html.erb, app/views/games/_game_paused.html.erb, app/views/games/_game_running.html.erb, app/views/games/show.html.erb
j'ai prepare les partials, et refait des test de js pour le broadcast.
=> Broadcast 28 02

app/views/games/_game_finished.html.erb
=> resolve bug result

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_image.scss, app/views/pages/home.html.erb, app/views/participations/new.html.erb
=> Mardi 03 03 5

app/controllers/answers_controller.rb, app/javascript/components/skipSong.js, app/javascript/packs/application.js, app/views/games/_game_running.html.erb, db/seeds.rb
la musique passe à la suivante quand elle est finie.
Au bout de 30 secondes, un form caché envoie la bonne réponse.
celle-ci est attribué au user ghost => User.first (rajouté dans les seeds)
Il faut encore gérer le tableau de résultat parce qu'il y a un bug (answering_time de ghost.answers = nil)
pas très compliqué je pense mais comme j'ai pas mal touché au fichier finished dans la dernière pull request, je préfère attendre que tout soit merger. pour éviter les conflits :)
=> Skipsongend

app/controllers/games_controller.rb, app/javascript/packs/application.js, app/views/games/_game_finished.html.erb, app/views/games/_game_running.html.erb, app/views/games/_navbar.html.erb
J'ai supprimé le destroy all answers à chaque création d'un nouveau game.
Le bouton rejouer fonctionne donc.
ça impliquait plusieurs modifs au niveau des scores en particulier mais aussi (bizarrement) pour la gestion de l'answering time... 
toutes les chansons ne redemarraient plus à 0.. 😱 mais au temps de la dernière réponse pour la chanson en question..
bref, j'ai galéré mais ça a l'air de fonctionner
Bises!
=> Removedestroyanswers

app/assets/stylesheets/components/_song-count.scss, app/javascript/components/flashSong.js, app/javascript/packs/application.js, app/views/games/_navbar.html.erb, db/seeds.rb
modification du compte de chanson.
À la première chanson, le premier point flash
À la deuxième, le premier point est blanc, le second flash
etc..
c'est plus clair pour savoir où on en est dans le jeu
=> flash icon of current track played

app/views/games/show.html.erb
création d'une bubble quand une chanson n'est pas trouvée.
permet d'afficher la réponse .
action cable pas encore géré. il faudrait que la bubble s'affiche chez tout le monde
=> create bubble for ghost answers

Gemfile.lock, app/javascript/packs/application.js, db/seeds.rb
j'ai changé le "calcul" du temps de réponse pour qu'il soit plus précis.
=> modifie answering time to be more specific

Procfile, config/puma.rb
configuration de puma pour la production
=> add procfile for production

app/controllers/answers_controller.rb, app/views/games/_game_finished.html.erb, db/migrate/20200331133235_add_score_to_answers.rb, db/schema.rb
Maintenant le calcul du score se fait depuis la classe Answer : 
la valeur de answer.score est créée dès que answer.status est vérifié (true ou false). Le calcul de answer.score se fait par la méthode answer_scoring dans AnswersController, en fonction du temps de réponse.
La view '_game_finished' en est considérablement allégée.
=> gestion des scores depuis la classe Answer

app/controllers/answers_controller.rb, app/controllers/games_controller.rb, app/controllers/participations_controller.rb, app/models/game.rb, app/models/participation.rb, app/views/games/_game_created.html.erb, app/views/games/_game_finished.html.erb, app/views/games/_game_paused.html.erb, app/views/games/show.html.erb, db/migrate/20200331133235_add_score_to_answers.rb, db/migrate/20200331174909_add_column_to_games.rb, db/migrate/20200331192618_add_column_total_score_to_participations.rb, db/schema.rb
total_score de chaque joueur : 
- @game.total_score donne le score total du MJ, initialisé à la création du game.
- @participation.total_score donne le socre total du participant, initialisé à la création de la participation.
=> Score model

app/assets/stylesheets/components/_home.scss, app/controllers/answers_controller.rb, app/jobs/playlist_job.rb, app/views/pages/home.html.erb, app/views/users/show.html.erb, config/sidekiq.yml, db/schema.rb
le titre de la **PR** n'est pas bon. j'ai finalement bossé sur le PlaylistJob
- permet de corriger des erreurs bizarre de spotify genre avoir du rnb dans rock ou des chansons non française dans la playlist french ...
- permet d'être certain que la playlist crée aura 5 élements (_j'ai eu le bug d'avoir des playlists avec seulement 2 titres_)
=> Dashboardusers

Procfile, config/initializers/redis.rb, db/seeds.rb
configuration de Redis pour Sidekiq en production : 
- Procfile modifié
- fichier initializer/redis.rb créé
ajout de seeds de answers
=> 07 04 sidekiq

app/assets/stylesheets/pages/_showuser.scss, app/controllers/answers_controller.rb, app/controllers/users_controller.rb, app/views/games/_game_finished.html.erb, app/views/users/show.html.erb
- ajout de **conditions** pour prévenir les bugs si le user n'a pas encore fait de parties
- clean des liens de la navbar. ils ne sont plus bleus mais de la même couleur que le texte
- lien vers dernier tableau de résulat inactif si il n'y pas de parties jouées
- place holder si aucun score
- **suppression** des liens vers les dashboards des users depuis le tableau de résultats
- _cela permet de récuperer la couleur verte des bonnes réponses_
=> Cleanshowuser

app/assets/stylesheets/pages/_showuser.scss, app/views/users/show.html.erb
- affichage de la playlist pour chacun des 3 meilleurs scores
- affichage de l'artiste et la chanson pour la réponse la plus rapide
- remplacement du lien vers le tableau de résultat (qui faisait une erreur 404) par un bouton retour
=> Last changes on dashboard

app/assets/stylesheets/pages/_showuser.scss, app/controllers/answers_controller.rb, app/views/users/show.html.erb
- j'ai rajouté des échelons pour le calcul du score pour éviter au maximum qu'on se retrouve avec trop de scores identiques
=> Newscoring

app/assets/stylesheets/pages/_showuser.scss, app/controllers/answers_controller.rb, app/javascript/channels/game_channel.js, app/views/users/show.html.erb
- j'ai modifié le fichier game_channel.js pour broadcaster le flashsong
=> Fixbroadcast

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_text-effect.scss, app/assets/stylesheets/pages/_game.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_showuser.scss, app/views/devise/sessions/new.html.erb, app/views/games/_game_finished.html.erb, app/views/games/edit.html.erb, app/views/pages/home.html.erb, app/views/users/show.html.erb
J'ai fixé les bugs de style : 
- le recouvrement du motif de background
- la taille de police
=> fix dashboard style bugs

app/views/pages/home.html.erb
button sur la home page
- fix margins
=> fix button on homepage

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
- fixé le style de la signup page comme les autres pages devise.
- réduit la largeur de formulaire sur écran moyen et grand
=> fix signup page style

app/controllers/users_controller.rb, app/models/answer.rb, app/models/user.rb, app/views/users/show.html.erb
- removed ghost from the score computings
- compute user.highest_score from the user model
=> 15 06 dashboard model
